apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: tuiv-backend
spec:
  type: ClusterIP
  selector:
    app: tuiv-backend
  ports:
    - name: http
      port: 8010
      targetPort: 8010
