---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tops-secret
  namespace: tops
spec:
  encryptedData:
    LLM_API_KEY: AgCp8tVwQXS/PPZxG1hYkD+9LSj0zaLicmAN2yhx9ZXeB+auD4QTCxcLqnsoPymKQ9t321XbUyCDU0Ss/HoFGf/yAZm5N+1Zn6ht+3hxjb6Bk9QZj3n+kTqqRHo+pxsdgIf2KYp9b1HDUHax2ljZ7kC71xB48wmgRVPrDmS2Ko7QaBf/wNghqHRQjJ5bHeuJQhIQsABOXtUAFDIAcR9F4x7MDyT9Xi/TGIRqZkVXjQp0OWpCkodj0jsw3IgrRPvgqMUgZA+g9bwIthoeKegmtZ9jE6rcHlVVfbKaPYTprn5dwSteOsD6CDkir3l9NySmJ8r9hvk7jiesZZ2YWs3FrJoWWxZHPnT/QgHaRQrNNAbryJez1cPARuDp0Twv9Fl5ksKHqIr6Ou+W7xMSmcoulcCGDT55ykHwetHG69lkEZP1PJSgThG138fVRNJbFvhRYS2AzzHO8Wf6eQXEQ1gc8eFjy0Hx9eGP8HH1F/xMEiYlVY40tr23EZgLFRMbBaEUKIqdPjBp5J1RNPQwjKyWuri2bqQNWQlbZUhbumTRXnstcB7n98FtLh5Hrwq+Nn2PezX0S3+9D5kIVvFoF02nMewCSloGJEXGiGOBXJ5gImKiUPVSV+iysl5fQLfvw0LnbyYahDlQdYQJv+QbeHtxEYHcp+LTUHv0K9LQzSYbU5j1oE7uSx0PY9CHr8dJ+FTji9ugx9ytBKre5MDJcIkwoylbzgKtF1IDQck9
  template:
    metadata:
      name: tops-secret
      namespace: tops
    type: Opaque
