apiVersion: apps/v1
kind: Deployment
metadata:
  name: tops-frontend
  labels:
    app: tops-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tops-frontend
  template:
    metadata:
      labels:
        app: tops-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/aihpi/pilotproject-protokollierungsassistenz/frontend:sha-4fe5ace
          ports:
            - containerPort: 80
          env:
            - name: NGINX_RESOLVER
              value: "rke2-coredns-rke2-coredns.kube-system.svc.k8s.test.sci.hpi.de"
            - name: NGINX_BACKEND
              value: "backend.tops.svc.cluster.local:8010"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
