apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-70b
  namespace: ollama-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: local-path
  volumeMode: Filesystem
